const caractere;


if (caractere === 'a' || caractere === 'e' || caractere === 'i' || caractere === 'o' || caractere === 'u') {
    console.log('Vogal minúscula.')
}
else if (caractere === 'A' || caractere === 'E' || caractere === 'I' || caractere === 'O' || caractere === 'U') {
    console.log('Vogal maiúscula.')
}
else if (caractere == 'b' || caractere == 'c' || caractere == 'd' || caractere == 'f' || caractere == 'g' || caractere == 'h' || caractere == 'j' || caractere == 'k' || caractere == 'l' || caractere == 'm' || caractere == 'n' || caractere == 'p' || caractere == 'q' || caractere == 'r' || caractere == 's' || caractere == 't' || caractere == 'v' || caractere == 'w' || caractere == 'x' || caractere == 'y' || caractere == 'z') {
    console.log('Isso é consoante.')
}
else if (caractere == 'B' || caractere == 'C' || caractere == 'D' || caractere == 'F' || caractere == 'G' || caractere == 'H' || caractere == 'J' || caractere == 'K' || caractere == 'L' || caractere == 'M' || caractere == 'N' || caractere == 'P' || caractere == 'Q' || caractere == 'R' || caractere == 'S' || caractere == 'T' || caractere == 'V' || caractere == 'W' || caractere == 'X' || caractere == 'Y' || caractere == 'Z') {
    console.log('Isso é consoante.')
}
else if (caractere === 0 || caractere === 1 || caractere === 2 || caractere === 3 || caractere === 4 || caractere === 5 || caractere === 6 || caractere === 7 || caractere === 8 || caractere === 9) {
    console.log('Isso é um número.')
}
else {
    console.log('Erro 404')
}